{
 "title": "BPI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PING STATS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pmin as value,\n  'pmin' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pavg as value,\n  'pavg' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pmax as value,\n  'pmax' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pminl as value,\n  'pminl' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pavgl as value,\n  'pavgl' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  pmaxl as value,\n  'pmaxl' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "ETH0 ERRORS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  rxok as value,\n  'rxok' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  txok as value,\n  'txok' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  rxdrp as value,\n  'rxdrp' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  txdrp as value,\n  'txdrp' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  rxerr as value,\n  'rxerr' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  txerr as value,\n  'txerr' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  rxovr as value,\n  'rxovr' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  txovr as value,\n  'txovr' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "MTU && SPEED ETH0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  mtu as value,\n  'mtu' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  eth0speed as value,\n  'eth0speed' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  mtot as value,\n  'mtot' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  mfree as value,\n  'mfree' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 1, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  cpu1 as value,\n  'cpu1' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  cpu2 as value,\n  'cpu2' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  cpu3 as value,\n  'cpu3' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  temp0 as value,\n  'temp0' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  temp1 as value,\n  'temp1' as metric\n FROM monitoring\nWHERE $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  }
 ]
}